include:
#  - board: nice_nano_v2
#    shield: tuball_left
    
  - board: nice_nano_v2
    shield: tuball4_right
#    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
#    snippet: zmk-usb-logging
   
  - board: nice_nano_v2
    shield: tuball4_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
#    snippet: zmk-usb-logging

  - board: nice_nano_v2
    shield: settings_reset
 